project:
  type: website

execute:
  freeze: auto

website:
  title: "Women in Campus Vietnam Protests"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - campus_protests.qmd
      - student_newspapers.qmd
      - about_the_sisters.qmd
      - text: The Seven Sisters
        menu:
        - barnard_college.qmd
        - bryn_mwar_college.qmd
        - mount_holyoke_college.qmd
        - radcliffe_college.qmd
        - smith_college.qmd
        - vassar_college.qmd
        - wellesley_college.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

